//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_msn_tuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int PostId { get; set; }
        public string Body { get; set; }
        public short Private { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Member Author { get; set; }
        public virtual Member Recipient { get; set; }
    }
}
