//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_msn_tuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int post_id { get; set; }
        public string body { get; set; }
        public short @private { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual members members { get; set; }
        public virtual members members1 { get; set; }
    }
}
